// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdw2wpjatn5fAbMw7vaRethD0tCQF_D-g',
    appId: '1:25253366847:web:a87478631024f35c66fc8a',
    messagingSenderId: '25253366847',
    projectId: 'imas-fleet-app',
    authDomain: 'imas-fleet-app.firebaseapp.com',
    storageBucket: 'imas-fleet-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDMGPSQauQAYc630Bv3onSIokwdZpqvS4',
    appId: '1:25253366847:android:2565d556306adaff66fc8a',
    messagingSenderId: '25253366847',
    projectId: 'imas-fleet-app',
    storageBucket: 'imas-fleet-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArRA4Mr_Edkj6yAquiuact0G6MZvqu4T8',
    appId: '1:25253366847:ios:15c1bc2528c37fe666fc8a',
    messagingSenderId: '25253366847',
    projectId: 'imas-fleet-app',
    storageBucket: 'imas-fleet-app.firebasestorage.app',
    iosBundleId: 'com.example.flutterTrial',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyArRA4Mr_Edkj6yAquiuact0G6MZvqu4T8',
    appId: '1:25253366847:ios:15c1bc2528c37fe666fc8a',
    messagingSenderId: '25253366847',
    projectId: 'imas-fleet-app',
    storageBucket: 'imas-fleet-app.firebasestorage.app',
    iosBundleId: 'com.example.flutterTrial',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAdw2wpjatn5fAbMw7vaRethD0tCQF_D-g',
    appId: '1:25253366847:web:b1ee42382daca5c066fc8a',
    messagingSenderId: '25253366847',
    projectId: 'imas-fleet-app',
    authDomain: 'imas-fleet-app.firebaseapp.com',
    storageBucket: 'imas-fleet-app.firebasestorage.app',
  );
}
